[package]
name = "yarnpkg-parsers"
version = "0.0.0"
license = "BSD-2-Clause"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "7.1.1"
nom-supreme = "0.8.0"
fnv = "1.0.7"
indexmap = { version = "1.9.1", features = ["serde"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
wasm-bindgen = "0.2.83"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O4']
