[package]
name = "yarnpkg-parsers"
version = "0.0.0"
license = "BSD-2-Clause"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "7.1.1"
nom-supreme = "0.8.0"
wasm-bindgen = "0.2.83"
# We need to preserve key order even though it's slower
serde_json = { version = "1.0.86", features = ["preserve_order"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O4']
